### ISSUE TITLE
Connect login and signup pages

### ISSUE THREAD

**Issue by ErlingHauan** [ErlingHauan/FormFactory#29]
Create links on each page to link to the other page. E.g Log in page needs a sign up button.

**Comment by rixitgithub** [comment]
i would like to attemp it

**Comment by rixitgithub** [comment]
How should i proceed?

**Comment by lassopicasso** [comment]
Hi @rixitgithub, appreciate your interest in contributing to the project. :) Unfortunately, the issue is already linked to this [pull request](https://github.com/ErlingHauan/FormFactory/pull/42). 
Nevertheless, we have numerous other issues labeled as `good first issue` in our main project. You can locate them by searching for our repository "altinn-studio" on https://forgoodfirstissue.github.com/
